version: '3.4'

volumes:
  dbVol1: {}

services:
  api:
    env_file: .env
    build:
      context: .
      target: dev
    container_name: vyaguta-workflow-api
    volumes:
      - ./:/app
    ports:
      - "3333:3333"
    image: vyaguta-workflow-api:0.0.1
    depends_on:
      - mongoDatabase
      - minioS3
  mongoDatabase:
    container_name: mongodb-service
    image: mongo:5.0.6
    restart: always
    volumes:
      - dbVol1:/data/db
    ports:
      - "27017:27017"
  minioS3:
    env_file: .env
    container_name: minio-s3
    image: minio/minio:RELEASE.2022-04-08T19-44-35Z
    restart: always
    ports:
      - "80:9000"
    command: "server /data --console-address \":80\""
  seed:
    env_file: .env
    build:
      context: .
      target: dev-setup
    depends_on:
      - mongoDatabase
